apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      # 프론트엔드 (SPA)
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-web-svc
            port:
              number: 80

      # API (나중에 Pod 살아나면 자동 연결)
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api-svc
            port:
              number: 3000

