apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: team2-api-ingress
  namespace: team2
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /weather$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api/weather(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: api-svc
            port:
              number: 3000

      - path: /api/energy(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: energy-api
            port:
              number: 8000

      - path: /api/map(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: map-api
            port:
              number: 80

